CC = gcc  
CFLAGS = -Wall -lpthread  

all: main.exe  

main.exe: src/main.c src/thread_pool.c  
	$(CC) $(CFLAGS) -o main.exe src/main.c src/thread_pool.c  

test.exe: tests/test_thread_pool.c src/thread_pool.c  
	$(CC) $(CFLAGS) -o test.exe tests/test_thread_pool.c src/thread_pool.c  
	.\test.exe  

clean:  
	del main.exe test.exe  